workflows:
  react-native:
    name: React Native App new
    environment:
      vars:
        XCODE_WORKSPACE: 'Apprene'
        XCODE_SCHEME: 'Apprene'

      node: latest
      xcode: latest
      cocoapods: default

    scripts:
      - cd android && chmod +x gradlew
      - npm install
      - echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
      - echo $(jq .'build' build_data/data.json)
      - |
        if [[ $(jq -r .'build' build_data/data.json) == "android" ]] || [[ $(jq -r ."build" build_data/data.json) == "both" ]] ; then
        echo "block executed";
        # build Android;
        cd android;
        ./gradlew assembleRelease;
        fi

      - |
        if [[ $(jq -r ."build" build_data/data.json) == "ios" ]] || [[ $(jq -r ."build" build_data/data.json) == "both" ]] ; then
        # build iOS
        cd ios
        pod install
        ls
        xcodebuild -scheme "$XCODE_SCHEME" -workspace "$XCODE_WORKSPACE.xcworkspace" -sdk iphonesimulator
        xcodebuild -scheme "$XCODE_SCHEME" -workspace "$XCODE_WORKSPACE.xcworkspace" -configuration Release clean archive -archivePath "Build/APPNAME.xcarchive" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO         
        xcodebuild -exportArchive -archivePath build/APPNAME.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/APPNAME.ipa
        fi

    artifacts:
      - android/app/build/outputs/**/*.apk

      - ios/Build/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/*-iphonesimulator/*.app
